fhikers_prototype v 5 0/fhikers_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from rutas import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rutas.urls')),

    path('welcome', views.welcome, name='welcome'),
    # path('register', views.register, name='register'),
    path('register', views.UserRegister.as_view(), name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),

]

fhikers_prototype v 5 0/rutas/urls.py
from django.urls import path
from . import views
from fhikers_proj.settings import DEBUG, STATIC_URL, STATIC_ROOT, MEDIA_URL, MEDIA_ROOT
from django.conf.urls.static import static

# from django.conf.urls import patterns, include, url
from django.conf.urls import include, url

urlpatterns = [
    path('', views.index, name = 'index'),
    path('ruta/<int:ruta_id>', views.ruta, name='ruta'),
    path('upload/', views.upload, name = 'upload-ruta'),
    path('update/<int:ruta_id>', views.update_ruta),
    path('delete/<int:ruta_id>', views.delete_ruta),

    # Stage
    path('upload_stage/', views.upload_stage, name='upload_stage'),
    path('ruta/update_stage/<int:stage_id>', views.update_stage, name='update_stage'),
    path('ruta/delete_stage/<int:stage_id>', views.delete_stage, name='delete_stage'),

    # Blog
    path('post/<int:id>', views.one_post, name="one_post"),
    path('category/<int:id>', views.posts_by_category, name="posts_by_category"),
    path('home/', views.home, name='home'),

    path('upload_post/', views.upload_post, name='upload_post'),
    path('ruta/update_post/<int:post_id>', views.update_post, name='update_post'),
    path('ruta/delete_post/<int:post_id>', views.delete_post, name='delete_post'),

    path('blog/', views.blog, name='blog'),

]

#DataFlair

if DEBUG:
    urlpatterns += static(STATIC_URL, document_root = STATIC_ROOT)
    urlpatterns += static(MEDIA_URL, document_root = MEDIA_ROOT)

fhikers_prototype v 5 0/rutas/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session

# Create your models here.


class Pais(models.Model):
    codigo_pais = models.CharField(max_length=2, blank=False, default='')
    nombre_pais = models.CharField(max_length=50, blank=False, default='')

    def __str__(self):
        cadena = self.codigo_pais + " - " + self.nombre_pais
        return cadena


class Usuario(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    OTHERS = 'O'
    GENDER_CHOICES = (
        (MALE, 'male'),
        (FEMALE, 'female'),
        (OTHERS, 'others'),
    )
    nombre = models.CharField(max_length=50, blank=False, default='')
    primer_apellido = models.CharField(max_length=50, blank=False, default='')
    segundo_apellido = models.CharField(max_length=50, blank=False, default='')
    sexo = models.CharField(max_length=1, choices=GENDER_CHOICES, default=FEMALE)
    fecha_nacimiento = models.DateField()
    email = models.EmailField()

    def __str__(self):
        return self.nombre


class Ruta(models.Model):
    LEVEL_CHOICES = (
        ('EASY', 'easy'),
        ('MODERATE', 'moderate'),
        ('HIGH', 'high'),
        ('CHALLENGING', 'challenging'),
    )
    foto = models.ImageField()
    titulo = models.CharField(max_length=100, blank=False, default='')
    descripcion = models.CharField(max_length=255, blank=False, default='')
    distancia = models.IntegerField()
    elevacion = models.IntegerField()
    tiempo_estimado = models.DurationField()
    nivel_dificultad = models.CharField(max_length=11, choices=LEVEL_CHOICES, default='EASY')
    numero_de_etapas = models.IntegerField()
    id_usuario = models.ForeignKey(User, on_delete=models.CASCADE, default='', blank=True, null=True)
    id_pais = models.ForeignKey(Pais, on_delete=models.CASCADE, default='', blank=True, null=True)

    def __str__(self):
        return self.titulo


class Etapa(models.Model):
    numero_etapa = models.IntegerField(blank=False, default=0)
    titulo_etapa = models.CharField(max_length=100, blank=False, default='')
    descripcion_etapa = models.CharField(max_length=255, blank=False, default='')
    id_ruta = models.ForeignKey(Ruta, on_delete=models.CASCADE, default='', blank=True, null=True)

    def __str__(self):
        return '%s' % (self.titulo_etapa)


class RelacionamentoUsuarioRuta(models.Model):
    id_usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    id_ruta = models.ForeignKey(Ruta, on_delete=models.CASCADE)
    interesado = models.CharField(max_length=50, blank=False, default='')
    recomienda = models.CharField(max_length=50, blank=False, default='')

    def __str__(self):
        return self.id_usuario


# BLOG


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Post(models.Model):
    # LEVEL_CHOICES2 = (
    #     ('EASY', 'easy'),
    #     ('MODERATE', 'moderate'),
    #     ('HIGH', 'high'),
    #     ('CHALLENGING', 'challenging'),
    # )
    title = models.CharField(max_length=200)
    content = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default='', blank=True, null=True)
    # category = models.CharField(max_length=11, choices=LEVEL_CHOICES2, default='EASY')
    id_usuario = models.ForeignKey(User, on_delete=models.CASCADE, default='', blank=True, null=True)
    id_ruta = models.ForeignKey(Ruta, on_delete=models.CASCADE, default='', blank=True, null=True)

    def __str__(self):
        return self.title

fhikers_prototype v 5 0/rutas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Ruta, Usuario, Etapa, Post, Category


# Forms


class UserForm(UserCreationForm):

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]
        labels = {
            'username': 'Username',
            'first_name': 'Name',
            'last_name': 'Surnames',
            'email': 'Email',
        }


class RutaCreate(forms.ModelForm):

    class Meta:
        model = Ruta
        # fields = '__all__'
        fields = ('foto','titulo','descripcion','distancia','elevacion','tiempo_estimado','nivel_dificultad','numero_de_etapas', 'id_pais', 'id_usuario')

        labels = {
            'foto': 'Foto',
            'titulo': 'Title',
            'descripcion': 'Description',
            'distancia': 'Distance (KM)',
            'elevacion': 'Elevation (M)',
            'tiempo_estimado': 'Estimated Time (00:00:00)',
            'nivel_dificultad': 'Difficulty',
            'numero_de_etapas': 'Number of Stages',
            'id_pais': 'Pais',
            'id_usuario': 'User',
        }


class EtapaForm(forms.ModelForm):

    class Meta:
        model = Etapa

        fields = [
            'numero_etapa',
            'titulo_etapa',
            'descripcion_etapa',
            'id_ruta',
        ]
        labels = {
            'numero_etapa': 'Stage Number',
            'titulo_etapa': 'Stage Title',
            'descripcion_etapa': 'Stage Description',
            'id_ruta': 'Stage ID',
        }


class PostForm(forms.ModelForm):
    class Meta:
        model = Post

        fields = [
            'title',
            'content',
            'category',
            'id_usuario',
            'id_ruta',
        ]
        labels = {
            'title': 'Title Blog',
            'content': 'Blog Content',
            'category': 'Category',
            'id_usuario': 'Author ID',
            'id_ruta': 'Route ID',
        }

fhikers_prototype v 5 0/rutas/views.py
from django.shortcuts import render, redirect
from .models import Ruta, Usuario, Etapa
from .forms import RutaCreate, UserForm, EtapaForm, PostForm
from django.http import HttpResponse

# Users imports
from django.contrib.auth import logout as do_logout
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as do_login

from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.urls import reverse_lazy

# Cuenta las rutas
from django.db.models import Count, Q

# Posts (Blog)
# from django.shortcuts import render_to_response   DEPRECATED (usar render)
from .models import Category
from .models import Post


# Create your views here.

def index(request):
    busqueda = request.GET.get("buscar")
    shelf = Ruta.objects.all()

    if busqueda:
        shelf = Ruta.objects.filter(
            Q(titulo__icontains=busqueda) |
            # Q(id_pais__icontains=busqueda) |
            Q(numero_de_etapas__icontains=busqueda) |
            Q(tiempo_estimado__icontains=busqueda) |
            Q(distancia__icontains=busqueda) |
            Q(elevacion__icontains=busqueda) |
            Q(nivel_dificultad__icontains=busqueda)
            ).distinct()

    return render(request, 'ruta/rutas.html', {'shelf': shelf, 'shelf_3': shelf[:3]})


def ruta(request, ruta_id):
    ruta_id = int(ruta_id)
    etapa_id = int(ruta_id)
    post_id = int(ruta_id)
    try:
        ruta_sel = Ruta.objects.get(id=ruta_id)
        etapa_sel = Etapa.objects.filter(id_ruta_id=etapa_id).order_by('numero_etapa')
        post_sel = Post.objects.filter(id_ruta_id=post_id).order_by('creation_date')
        # etapa_sel = Etapa.objects.filter(id_ruta_id=etapa_id).order_by('numero_etapa')
    except Ruta.DoesNotExist:
        return redirect('index')
    return render(request, ('ruta/ruta.html', 'ruta/etapa.html', 'ruta/upload_post.html'), {'ruta_data': ruta_sel, 'etapa_data': etapa_sel, 'post_data': post_sel})


# CRUD Rutas


def upload(request):
    upload = RutaCreate()
    if request.method == 'POST':
        upload = RutaCreate(request.POST, request.FILES)
        if upload.is_valid():
            upload.save()
            return redirect('index')
        else:
            return HttpResponse(""" your form is wrong, reload on <a href = "{{ url : 'index'}}">reload</a>""")
    else:
            return render(request, 'ruta/upload_form.html', {'upload_form':upload})


def update_ruta(request, ruta_id):
    ruta_id = int(ruta_id)
    try:
        ruta_sel = Ruta.objects.get(id=ruta_id)
    except Ruta.DoesNotExist:
        return redirect('index')
    ruta_form = RutaCreate(request.POST or None, instance=ruta_sel)
    if ruta_form.is_valid():
       ruta_form.save()
       return redirect('index')
    return render(request, 'ruta/upload_form.html', {'upload_form': ruta_form})


def delete_ruta(request, ruta_id):
    ruta_id = int(ruta_id)
    try:
        ruta_sel = Ruta.objects.get(id = ruta_id)
    except Ruta.DoesNotExist:
        return redirect('index')
    ruta_sel.delete()
    return redirect('index')


# Sistema de registro de usuarios

def welcome(request):
    shelf = Ruta.objects.filter(id_usuario=request.user.id)
    # Si estamos identificados devolvemos la portada
    if request.user.is_authenticated:
        # return render(request, "welcome.html", {'shelf': shelf, 'total': total})
        return render(request, "welcome.html", {'shelf': shelf})
    # En otro caso redirecionamos al login
    return redirect(request, '/login')


# Clase utilizada en lugar de la funcion register
class UserRegister(CreateView):
    model = User
    template_name = "register.html"
    form_class = UserForm
    success_url = reverse_lazy('login')


def login(request):
    # Creamos el formulario de autenticación vacío
    form = AuthenticationForm()
    if request.method == "POST":
        # Añadimos los datos recibidos al formulario
        form = AuthenticationForm(data=request.POST)
        # Si el formulario es válido...
        if form.is_valid():
            # Recuperamos las credenciales validadas
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # Verificamos las credenciales del usuario
            user = authenticate(username=username, password=password)

            # Si existe un usuario con ese nombre y contraseña
            if user is not None:
                # Hacemos el login manualmente
                do_login(request, user)
                # Y le redireccionamos a la portada

                # return redirect('/')
                return redirect('welcome')

    # Si llegamos al final renderizamos el formulario
    return render(request, "login.html", {'form': form})


def logout(request):
    # Finalizamos la sesión
    do_logout(request)
    # Redireccionamos a la portada
    return redirect('/')



# CRUD Stages


def upload_stage(request):
    upload = EtapaForm()
    if request.method == 'POST':
        upload = EtapaForm(request.POST, request.FILES)
        if upload.is_valid():
            upload.save()
            return redirect('index')
        else:
            return HttpResponse(""" your form is wrong, reload on <a href = "{{ url : 'index'}}">reload</a>""")
    else:
            return render(request, 'ruta/ruta.html', {'upload_stage_form':upload})


def update_stage(request, stage_id):
    stage_id = int(stage_id)
    try:
        stage_sel = Etapa.objects.get(id=stage_id)
    except Etapa.DoesNotExist:
        return redirect('index')
    stage_form = EtapaForm(request.POST or None, instance=stage_sel)
    if stage_form.is_valid():
       stage_form.save()
       return redirect('index')
    return render(request, 'ruta/update_etapa.html', {'upload_form': stage_form})


def delete_stage(request, stage_id):
    stage_id = int(stage_id)
    try:
        stage_sel = Etapa.objects.get(id = stage_id)
    except Ruta.DoesNotExist:
        return redirect('index')
    stage_sel.delete()
    return redirect('index')


# POSTS  consultas (BLOG)

def one_post(request, idpost):
    post = Post.objects.get(id=idpost)

    return render(request, 'ruta/ruta.html', {"post": post})
    # ("post.html",{"post": post,},)


def home(request):
    posts = Post.objects.order_by("-creation_date")     # El - es para invertir el orden

    return render(request, 'ruta/home.html', {"posts": posts})


def posts_by_category(request, idcategory):
    category = Category.objects.get(id=idcategory)
    posts = category.post_set.order_by("-creation_date")

    return render(request, 'ruta/home.html', {"posts": posts})
    # ("home.html",{"posts": posts,},)



# CRUD POSTS (BLOG)

def upload_post(request):
    ruta_id = 'ruta_data.id'
    upload = PostForm()
    if request.method == 'POST':
        upload = PostForm(request.POST, request.FILES)
        if upload.is_valid():
            upload.save()
            return redirect('index')
        else:
            return HttpResponse(""" your form is wrong, reload on <a href = "{{ url : 'index'}}">reload</a>""")
    else:
            return render(request, 'ruta/ruta.html', {'upload_post_form':upload})


def update_post(request, post_id):
    post_id = int(post_id)
    try:
        post_sel = Post.objects.get(id=post_id)
    except Post.DoesNotExist:
        return redirect('index')
    post_form = PostForm(request.POST or None, instance=post_sel)
    if post_form.is_valid():
       post_form.save()
       return redirect('index')
    return render(request, 'ruta/update_etapa.html', {'upload_form': post_form})


def delete_post(request, post_id):
    post_id = int(post_id)
    try:
        post_sel = Post.objects.get(id = post_id)
    except Ruta.DoesNotExist:
        return redirect('index')
    post_sel.delete()
    return redirect('index')


def blog(request):
    posts = Post.objects.all()
    return render(request, 'ruta/blog.html', {"posts": posts})

fhikers_prototype v 5 0/rutas/templates/ruta/base.html
<!DOCTYPE html>
<html>
    <head>
    <title>{% block title %}{% endblock %}</title>
    </head>

    <body>
    {% block content %}{% endblock %}
    </body>
</html>

fhikers_prototype v 5 0/rutas/templates/ruta/blog.html
{% extends 'ruta/rutas.html' %}
{% load static %}
{% block content %}
<!--    Posts  -->
  <center>
      <br><br><br>
      <div width="80%">
        <img width="80%" src="/media/blog_img.jpg" class="img-fluid" alt="FHikers" style="color:white;">
      </div>
      <br><br><br>
      <h1>Posts</h1>

      <br><br>
      {% for post in posts %}
        <div class="card bg-light mb-3" style="max-width: 98%;" align="left">
          <div class="card-header">
            <strong>{{ post.title }}</strong>
            <p class="text-right">Route reference: {{ post.id_ruta }}</p>
          </div>
            <div class="card-body">
              <p class="card-text"><small class="text-muted">{{ post.creation_date }}</small></p>
              <p class="card-text">{{ post.content }}</p>
              <p class="text-right">Author: {{ post.id_usuario }}</p>
              {% if request.user.is_authenticated %}
              <div align="right">
                <a href="update_post/{{post.id}}" class="btn btn-warning" id = '{{post.id}}'>Edit</a>
                <a href="delete_post/{{post.id}}" class="btn btn-danger" onClick="return confirm('¿Are you sure to delete {{ post.titulo_etapa }}?');" id = '{{post.id}}'>Delete</a>
              </div>
              {% endif %}
            </div>
        </div>
        <br>
      {% endfor %}
      <br><br><br>
  </center>

  <div class="card-body">
    {% if request.user.is_authenticated %}
      <h5 class="card-title">Create a new post</h5>
      <p>
        <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample2" role="button" aria-expanded="false" aria-controls="collapseExample">
          Create Post
        </a>
      </p>
      <div id="collapseExample2" class="collapse card card-body container well card">
            <h5 style="padding-top:1em;">Create Post</h5>
            {% include 'ruta/upload_post.html' %}
      </div>
    {% endif %}
    <br><br><br>
  </div>

{% endblock content %}

fhikers_prototype v 5 0/rutas/templates/ruta/etapa.html
{% extends 'ruta/rutas.html' %}

{% block content %}

<form method="POST" action="{% url 'upload_stage' %}">
   {% csrf_token %}
    <br><br><br>
     <div class="row">
          <div class="col-md-5 col-md-offset-2">
              <div class="form-group">
                <label for="first_name">Stage Number</label>
                <input type="text" class="form-control" id="numero_etapa" name="numero_etapa">
              </div>
          </div>
      </div>
      <div class="row">
          <div class="col-md-5 col-md-offset-2">
              <div class="form-group">
                <label for="first_name">Stage Title</label>
                <input type="text" class="form-control" id="titulo_etapa" name="titulo_etapa">
              </div>
          </div>
      </div>
      <div class="row">
          <div class="col-md-5 col-md-offset-2">
              <div class="form-group">
                <label for="last_name">Stage Description</label>
                <input type="text" class="form-control" id="descripcion_etapa" name="descripcion_etapa">
              </div>
          </div>
      </div>
      <div class="row" style="display:none">
          <div class="col-md-5 col-md-offset-2">
              <div class="form-group">
                <label for="last_name">Stage Ruta ID</label>
                <input type="text" class="form-control" id="id_ruta" name="id_ruta" value="{{ruta_data.id}}">
              </div>
          </div>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
      <br><br>
    </form>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

{% endblock content %}

fhikers_prototype v 5 0/rutas/templates/ruta/home.html
{% extends 'ruta/base.html' %}

{% block title %}Mi blog{% endblock %}

{% block content %}

    <h1>Posts</h1>

    {% for post in posts %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.content }}</p>
        <p>{{ post.id_ruta}}</p>
        <p>{{ post.id_usuario}}</p>
        <hr>
    {% endfor %}

{% endblock %}

fhikers_prototype v 5 0/rutas/templates/ruta/post.html
{% extends 'ruta/base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p>{{ post.content }}</p>
    <p>{{ post.id_ruta}}</p>
    <p>{{ post.id_usuario}}</p>
{% endblock %}

fhikers_prototype v 5 0/rutas/templates/ruta/update_etapa.html
{% extends 'ruta/rutas.html' %}

{% block content %}

    <center>
        <br>
        <h1 class="display-4 text-center alert alert-light" style="color:#34626c;">Upload Stage</h1>
        <hr>

        <form method = 'POST' enctype="multipart/form-data">
            {% csrf_token %}

            <table class = 'w-50 table table-light' style="border-radius:10px;background-color:#cfd3ce;color:#34626c;">
                {% for field in upload_form %}

                    {% if field.name == 'id_ruta' %}
                        <tr style="display:none">
                            <th>{{field.label}}</th>
                            <td>{{ field }}</td>
                            <td>{{ field.help_text }}</td>
                        </tr>

                        <!--
                        <tr style="display:none">
                            <th>Id ruta</th>
                            <td><input type="text" name="id_ruta" maxlength="10" required="" id="id_id_ruta" value="{{ruta_data.id}}"></td>
                            <td></td>
                        </tr>
                        -->
                    {% else %}
                        <tr>
                            <th>{{field.label}}</th>
                            <td>{{ field }}</td>
                            <td>{{ field.help_text }}</td>
                        </tr>
                    {% endif %}

                {% endfor %}
            </table>

            <button type="submit" class="btn btn-lg btn-warning">Submit</button>

        </form>
    </center>
    <br><br><br>

{% endblock %}

fhikers_prototype v 5 0/rutas/templates/ruta/update_post.html
{% extends 'ruta/rutas.html' %}

{% block content %}

    <center>
        <br>
        <h1 class="display-4 text-center alert alert-light" style="color:#34626c;">Upload Stage</h1>
        <hr>

        <form method = 'POST' enctype="multipart/form-data">
            {% csrf_token %}

            <table class = 'w-50 table table-light' style="border-radius:10px;background-color:#cfd3ce;color:#34626c;">
                {% for field in upload_form %}

<!--                    {% if field.name == 'id_ruta' %}-->
                    {% if field.name == 'id' %}
                        <tr style="display:none">
                            <th>{{field.label}}</th>
                            <td>{{ field }}</td>
                            <td>{{ field.help_text }}</td>
                        </tr>

                        <!--
                        <tr style="display:none">
                            <th>Id ruta</th>
                            <td><input type="text" name="id_ruta" maxlength="10" required="" id="id_id_ruta" value="{{ruta_data.id}}"></td>
                            <td></td>
                        </tr>
                        -->
                    {% else %}
                        <tr>
                            <th>{{field.label}}</th>
                            <td>{{ field }}</td>
                            <td>{{ field.help_text }}</td>
                        </tr>
                    {% endif %}

                {% endfor %}
            </table>

            <button type="submit" class="btn btn-lg btn-warning">Submit</button>

        </form>
    </center>
    <br><br><br>

{% endblock %}

fhikers_prototype v 5 0/rutas/templates/ruta/upload_form.html
{% extends 'ruta/rutas.html' %}

{% block content %}

    <center>
        <br>
        <h1 class="display-4 text-center alert alert-light" style="color:#34626c;">Upload Rutas</h1>
        <hr>

        <form method = 'POST' enctype="multipart/form-data">
            {% csrf_token %}

            <table class = 'w-50 table table-light' style="border-radius:10px;background-color:#cfd3ce;color:#34626c;">
                {% for field in upload_form %}

                    {% if field.name == 'id_usuario' %}
                        <tr style="display:none">
                            <th>Id usuario</th>
                            <td><input type="text" name="id_usuario" maxlength="10" required="" id="id_id_usuario" value="{{request.user.id}}"></td>
                            <td></td>
                        </tr>
                    {% else %}
                        <tr>
                            <th>{{field.label}}</th>
                            <td>{{ field }}</td>
                            <td>{{ field.help_text }}</td>
                        </tr>
                    {% endif %}

                {% endfor %}
            </table>


            <!--
            <table class = 'w-50 table table-light' style="border-radius:10px;background-color:#cfd3ce;color:#34626c;">

                <tr>
                    <th>Foto</th>
                    <td><input type="file" name="foto" accept="image/*" required="" id="id_foto"></td>
                    <td></td>
                </tr>

                <tr>
                    <th>Titulo</th>
                    <td><input type="text" name="titulo" maxlength="100" required="" id="id_titulo"></td>
                    <td></td>
                </tr>

                <tr>
                    <th>Descripcion</th>
                    <td><input type="text" name="descripcion" maxlength="255" required="" id="id_descripcion"></td>
                    <td></td>
                </tr>

                <tr>
                    <th>Distancia</th>
                    <td><input type="text" name="distancia" maxlength="10" required="" id="id_distancia"></td>
                    <td></td>
                </tr>

                <tr>
                    <th>Elevacion</th>
                    <td><input type="text" name="elevacion" maxlength="10" required="" id="id_elevacion"></td>
                    <td></td>
                </tr>

                <tr>
                    <th>Tiempo estimado</th>
                    <td><input type="text" name="tiempo_estimado" required="" id="id_tiempo_estimado"></td>
                    <td></td>
                </tr>

                <tr>
                    <th>Nivel dificultad</th>
                    <td><input type="text" name="nivel_dificultad" maxlength="10" required="" id="id_nivel_dificultad"></td>
                    <td></td>
                </tr>

                <tr>
                    <th>Numero de etapas</th>
                    <td><input type="number" name="numero_de_etapas" required="" id="id_numero_de_etapas"></td>
                    <td></td>
                </tr>

                <tr style="display:none">
                    <th>Id usuario</th>
                    <td><input type="text" name="id_usuario" maxlength="10" required="" id="id_id_usuario" value="{{request.user.id}}"></td>
                    <td></td>
                </tr>

                <!--
                <tr>
                    <th>Id usuario</th>
                    <td><select name="id_usuario" id="id_id_usuario" etiqueta="" html="" class="">
                        <option selected="" value="{{request.user.id}}">{{request.user.id}}</option>
                    </select></td>
                    <td></td>
                </tr>
                --

            </table>
            -->

            <button type="submit" class="btn btn-lg btn-warning">Submit</button>

        </form>
    </center>
    <br><br><br>

{% endblock %}